import { ApolloWrapper } from '@/lib/apollo-wrapper'
import type { Metadata } from 'next'
import QueryClientWrapper from '../lib/query-client-wrapper'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <QueryClientWrapper>{children}</QueryClientWrapper>
        </ApolloWrapper>
      </body>
    </html>
  )
}
